{% set name = "sas_kernel" %}
{% set version = "2.4.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/SAS_kernel-{{ version }}.tar.gz
  sha256: 7f8f447e9b60d2501ef772bde29db6afacf496434b3336037ddb8b89d3028857

build:
  noarch: python
  script: NO_KERNEL_INSTALL=1 {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - metakernel >=0.27.5
    - jupyter_client >=6
    - ipython >=7
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.9
    - saspy >=3.6
    - metakernel >=0.27.5
    - jupyter_client >=6
    - ipython >=7

test:
  imports:
    - sas_kernel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sassoftware/sas_kernel
  summary: A SAS kernel for Jupyter
  license: Apache-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - izahn
