{% set version = "2.2.0" %}

package:
  name: sas_kernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sas_kernel/SAS_kernel-{{ version }}.tar.gz
  sha256: 3ebddf4a85311b718acf12f56cc342f808039e83771cf0ae2b1f2f163c98c6b8

build:
  number: 1001
  script: "NO_KERNEL_INSTALL=1 {{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true  # [not linux]
  skip: true  # [py2k]

requirements:
  build:
    - python 
    - pip
    - ipython >=4
  run:
    - python
    - ipython >=4
    - saspy >=1.2.2
    - pygments
    - metakernel >=0.18.0
    - jupyter_client >=4.4.0

test:
  imports:
    - sas_kernel

about:
  home: https://github.com/sassoftware/sas_kernel
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: A Jupyter kernel for SAS

extra:
  recipe-maintainers:
    - danielfrg
