{% set version = "2.4.6" %}

package:
  name: sas_kernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sas_kernel/SAS_kernel-{{ version }}.tar.gz
  sha256: 54fdf913442872a8a2b13b3ae5e104d5bc9171725487904e5a151587ca9b7dd5

build:
  number: 0
  script: NO_KERNEL_INSTALL=1 {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [not linux]
  skip: true  # [py2k]

requirements:
  host:
    - python
    - pip
    - ipython >=4
  run:
    - python
    - ipython >=4
    - saspy >=1.2.2
    - pygments
    - metakernel >=0.18.0
    - jupyter_client >=4.4.0

test:
  imports:
    - sas_kernel

about:
  home: https://github.com/sassoftware/sas_kernel
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: A Jupyter kernel for SAS

extra:
  recipe-maintainers:
