{% set name = "sas_kernel" %}
{% set version = "2.4.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/SAS_kernel-{{ version }}.tar.gz
  sha256: 7bd05f0d071ab975d8cac6ee1eb1ee0d19c47d69121afddc6c0b47bd044983f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - metakernel >=0.27.5
    - jupyter_client >=6
    - ipython >=7
    - pip
  run:
    - python >=3.8
    - saspy >=3.6
    - metakernel >=0.27.5
    - jupyter_client >=6
    - ipython >=7

test:
  imports:
    - sas_kernel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sassoftware/sas_kernel
  summary: A SAS kernel for Jupyter
  license: Apache-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - izahn
