appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gIvzDvYyhKGku9T4fJuWwPPIRxCxXdCp8OzFg3BBsyayND9Og0BxxWCZVD/WbR4G9BmH+9H6xSk2O2XtT6e07GgAPaQ4Fz7AYdW036BIl+uZW1bLxfk8WCWfkZTsGpz24prEjXPm9CDeF82sn2axcljCHUhTnMrXZPSf0Pbj/Mi0PrenQevtFSshMDAVWN/0Fy1G5qFrBSmESNLONzAPRQcbDX+qMRdvfcSTBsjEv0jkgSLm/wNIf8ExdP+ewHxtU9XOQZxQzNMufL37B1W6D0+mhvXeRxzlkW83vBhBz640M6UCvOoc0dvw1p5Xh6UIFVaa64An/Up+7AnLCTF6hzS7pOzU2mjsJx5gLWOvs9hsWRK2c0mOLn8YaQfjmimTrlUPpzz8k+k3EIs6RGy6J2EfQ8oJUhs/Bc2WxeVI0p2Gm3gD6wMaPTSPH9fgjfHms6gdBjjRmdIhRwkcRHFtc+kQaAWNSRouc5aTcNn1o87zEbEV86uLoWQyu5sorRmmIk7lx7aemV629n5Ai7fOcm75UBI/jVLtcJbNN2ucB0kQJpIasBZRRZYKuIfDaxHyuEopvUurLi39jEHF0Zcka9gEHZL2c3bkErzbKF+3dWjUdzOrcHO4EJ3gRkD79uDGATMMv1I0eDUUSmDzdOi5gytb5LWSPDN4THHiIMSdjKY=}
